[Writable]
  LogLevel = "INFO"
  [Writable.Device]
    DataTransform = true
    MaxCmdOps = 128
    MaxCmdResultLen = 256

[Service]
  Host = "edgex-device-grove"
  ServerBindAddr = "0.0.0.0"
  Port = 59992
  StartupMsg = "device Grove PI started"
  ReadMaxLimit = 256
  RequestTimeout = "5s"
  HealthCheckInterval = "10s"

[Clients]
  [Clients.core-data]
    Host = "edgex-core-data"
    Port = 59880

  [Clients.core-metadata]
    Host = "edgex-core-metadata"
    Port = 59881

[Device]
  ProfilesDir = "./res/profiles"
  DevicesDir = "./res/devices"
  UseMessageBus = true

[Driver]
  BME680_Temp_Offset = -1.0

[MessageQueue]
  Protocol = "redis"
  Host = "localhost"
  Port = 6379
  Type = "redis"
  PublishTopicPrefix = "edgex/events/device" # /<device-profile-name>/<device-name>/<source-name> will be added to this Publish Topic prefix
  [MessageQueue.Optional]
    ClientId = "device-grove"
    Qos = 0 # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
    KeepAlive = 10 # Seconds (must be 2 or greater)
    Retained = false
